### ISSUE TITLE
Add ttvlol flag

### ISSUE THREAD

**Issue by daspryJ** [piero0920/Twitch-Archive#1]
To have recordings with less interruptions, it would be nice to have an option to easily add ttvlol flag(https://github.com/2bc4/streamlink-ttvlol) to steamlink call.

Btw, I see an option to delete ts files, then what does it ouput, is it configurable? I want mainly to record audio_only, so it would be weird to put it in mp4s. I prefer only ts anyway, if need be, to edit the audio files before uploading it, it's better to do it from raws than accumulate lossy encodings. But i don't see the option of only ts.

**Comment by piero0920** [comment]
I added the ttvlol flag, `--ttv-lol` obviously everybody has to add the plugin to their end to work. 

The option to delete ts files is mainly if you don't want to have two big files that are basically the same, now the output is mp4/mp3. the raw files are only for the recording, since uses Streamlink, the VOD uses [TwitchDownloaderCLI](https://github.com/lay295/TwitchDownloader), because downloading VOD with Streamlink takes a lot of time. 
Inside the `twitch-archive.py` I added the only-raw option to leave only the raw option (ts files) and not convert it to mp4/mp3.
